dist: xenial
language: cpp
addons:
  apt:
    packages:
      - curl
      - cmake
      - nasm
      - libcurl4-gnutls-dev
      - libedit-dev
      - zlib1g-dev
      - libgl1-mesa-dev
      - libpcre3-dev
      - libavutil-dev
      - libx11-dev
      - libglu1-mesa-dev
      - libglew-dev
      - libavcodec-dev
      - libavformat-dev
      - libavresample-dev
      - libcairo2-dev
      - libpango1.0-dev
      - libglibmm-2.4-dev
      - libpng-dev
      - libjpeg-dev
      - librtmp-dev
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libgnutls28-dev
      - liblzma-dev
script: cmake . && make

matrix:
  include:
    - name: Windows 64-bit
      sudo: required
      env: PATH=/usr/lib/mxe/usr/bin:$PATH
      addons:
        apt:
          sources:
            - sourceline: 'deb http://pkg.mxe.cc/repos/apt xenial main'
              key_url: 'https://keyserver.ubuntu.com/pks/lookup?search=0xC6BF758A33A3A276&op=get'
          packages:
            - nasm
            - libtool
            - libtool-bin
            - gperf
            - lzip
            - p7zip-full
            - intltool
            - mxe-x86-64-w64-mingw32.static-cc
            - mxe-x86-64-w64-mingw32.static-glibmm
            - mxe-x86-64-w64-mingw32.static-cairo
            - mxe-x86-64-w64-mingw32.static-pango
            - mxe-x86-64-w64-mingw32.static-jpeg
            - mxe-x86-64-w64-mingw32.static-glew
            - mxe-x86-64-w64-mingw32.static-freetype
            - mxe-x86-64-w64-mingw32.static-curl
            - mxe-x86-64-w64-mingw32.static-librtmp
            - mxe-x86-64-w64-mingw32.static-ffmpeg
            - mxe-x86-64-w64-mingw32.static-sdl2-mixer
      script:
          - (cd /usr/lib/mxe/ &&
             sudo make settings.mk &&
             sudo sed -i -e "s/SKIPPLUGINS='System'/SKIPPLUGINS=''/" src/nsis.mk &&
             sudo sed -i -e "s/.*MXE_TARGETS.*/MXE_TARGETS := x86_64-w64-mingw32.static/" settings.mk &&
             sudo make nsis)
          - x86_64-w64-mingw32.static-cmake .
          - make
          - sed -i -e "s/Lightspark Team/The Lightspark Developers/g" CPackConfig.cmake
          - make package
      deploy:
        provider: releases
        draft: true
        api_key: '$GITHUB_API_KEY'
        file_glob: true
        file:
          - ./*.exe
          - x86_64/Releases/**/*
        skip_cleanup: true
        on:
            tags: true
    - name: Windows 32-bit
      sudo: required
      env: PATH=/usr/lib/mxe/usr/bin:$PATH
      addons:
        apt:
          sources:
            - sourceline: 'deb http://pkg.mxe.cc/repos/apt xenial main'
              key_url: 'https://keyserver.ubuntu.com/pks/lookup?search=0xC6BF758A33A3A276&op=get'
          packages:
            - nasm
            - libtool
            - libtool-bin
            - gperf
            - lzip
            - p7zip-full
            - intltool
            - mxe-i686-w64-mingw32.static-cc
            - mxe-i686-w64-mingw32.static-glibmm
            - mxe-i686-w64-mingw32.static-cairo
            - mxe-i686-w64-mingw32.static-pango
            - mxe-i686-w64-mingw32.static-jpeg
            - mxe-i686-w64-mingw32.static-glew
            - mxe-i686-w64-mingw32.static-freetype
            - mxe-i686-w64-mingw32.static-curl
            - mxe-i686-w64-mingw32.static-librtmp
            - mxe-i686-w64-mingw32.static-ffmpeg
            - mxe-i686-w64-mingw32.static-sdl2-mixer
      script:
          - (cd /usr/lib/mxe/ &&
             sudo make settings.mk &&
             sudo sed -i -e "s/SKIPPLUGINS='System'/SKIPPLUGINS=''/" src/nsis.mk &&
             sudo sed -i -e "s/.*MXE_TARGETS.*/MXE_TARGETS := i686-w64-mingw32.static/" settings.mk &&
             sudo make nsis)
          - i686-w64-mingw32.static-cmake .
          - make
          - sed -i -e "s/Lightspark Team/The Lightspark Developers/g" CPackConfig.cmake
          - make package
      deploy:
        provider: releases
        draft: true
        api_key: '$GITHUB_API_KEY'
        file_glob: true
        file:
          - ./*.exe
          - i686/Releases/**/*
        skip_cleanup: true
        on:
            tags: true

    - name: Ubuntu 18.04
      addons:
        apt:
          packages:
      script:
          - docker pull ubuntu:18.04
          - docker run -v $PWD:/root/src ubuntu:18.04
                 bash -c 'apt update && apt install -y
                 curl
                 cmake
                 nasm
                 libcurl4-gnutls-dev
                 libedit-dev
                 zlib1g-dev
                 libgl1-mesa-dev
                 libpcre3-dev
                 libavutil-dev
                 libx11-dev
                 libglu1-mesa-dev
                 libglew-dev
                 libavcodec-dev
                 libavformat-dev
                 libavresample-dev
                 libcairo2-dev
                 libpango1.0-dev
                 libglibmm-2.4-dev
                 libpng-dev
                 libjpeg-dev
                 librtmp-dev
                 libsdl2-dev
                 libsdl2-mixer-dev
                 libgnutls28-dev
                 liblzma-dev && cd /root/src && cmake . && make'
    - name: Ubuntu 16.04
    - name: Clang 8.0
      env:
        - MATRIX_EVAL="CC=clang-8 CXX=clang++-8"
      before_install:
        - eval "${MATRIX_EVAL}"
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'https://keyserver.ubuntu.com/pks/lookup?search=0x15CF4D18AF4F7421&op=get'
          packages:
            - curl
            - cmake
            - nasm
            - clang-8
            - libcurl4-gnutls-dev
            - libedit-dev
            - zlib1g-dev
            - libgl1-mesa-dev
            - libpcre3-dev
            - libavutil-dev
            - libx11-dev
            - libglu1-mesa-dev
            - libglew-dev
            - libavcodec-dev
            - libavformat-dev
            - libpng-dev
            - libjpeg-dev
            - librtmp-dev
            - libsdl2-dev
            - libsdl2-mixer-dev
            - libgnutls28-dev
            - liblzma-dev
    - name: Clang Nightly
      allow_failures: true
      env:
        - MATRIX_EVAL="CC=clang CXX=clang++"
      before_install:
        - eval "${MATRIX_EVAL}"
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main'
              key_url: 'https://keyserver.ubuntu.com/pks/lookup?search=0x15CF4D18AF4F7421&op=get'
          packages:
            - curl
            - cmake
            - nasm
            - clang
            - libcurl4-gnutls-dev
            - libedit-dev
            - zlib1g-dev
            - libgl1-mesa-dev
            - libpcre3-dev
            - libavutil-dev
            - libx11-dev
            - libglu1-mesa-dev
            - libglew-dev
            - libavcodec-dev
            - libavformat-dev
            - libpng-dev
            - libjpeg-dev
            - librtmp-dev
            - libsdl2-dev
            - libsdl2-mixer-dev
            - libgnutls28-dev
            - liblzma-dev
